{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rabbitmq.name" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
data:
  enabled_plugins: |
    [rabbitmq_peer_discovery_k8s, rabbitmq_management,rabbitmq_stomp].
  rabbitmq.conf: |
    cluster_formation.peer_discovery_backend = k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = hostname
    cluster_formation.k8s.service_name = {{ include "rabbitmq.name" . }}-headless
    queue_master_locator=min-masters
  {{- toYaml .Values.configmap.additionalData | nindent 2 -}}
{{- end}}