apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rabbitmq.name" . }}-data
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{.Values.pvcData.accessMode}}
  resources:
    requests:
      storage: {{.Values.pvcData.storage}}
  storageClassName: {{ .Values.pvcData.storageClassName }}