{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "rabbitmq.name" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.secret.data | nindent 2 -}}
{{- end }}
